# pandas练习4－排序、排名、数据合并

## 任务一：排名与排序

### 1.1 数据读取
利用read_table()方法读取'rz4.txt'文件中的数据，并保存至自定义的DataFrame对象中；

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams["font.sans-serif"] = ["SimHei"]
plt.rcParams["axes.unicode_minus"] = False # 显示中文属性设置

In [6]:
file_path = 'rz4.txt'
df = pd.read_table(file_path, delimiter='\t', header=None)
df

                                                 0
0                学号 班级 姓名 性别 英语 体育 军训 数分 高代 解几 计算机
1    2308024241 23080242 成龙 男 76 78 77 40 23 60 89
2    2308024244 23080242 周怡 女 66 91 75 47 47 44 82
3    2308024251 23080242 张波 男 85 81 75 45 45 60 80
4    2308024249 23080242 朱浩 男 65 50 80 72 62 71 82
5    2308024219 23080242 封印 女 73 88 92 61 47 46 83
6    2308024201 23080242 迟培 男 60 50 89 71 76 71 82
7    2308024347 23080243 李华 女 67 61 84 61 65 78 83
8    2308024307 23080243 陈田 男 76 79 86 69 40 69 82
9    2308024326 23080243 余皓 男 66 67 85 65 61 71 95
10   2308024320 23080243 李嘉 女 62 60 90 60 67 77 95
11  2308024342 23080243 李上初 男 76 90 84 60 66 60 82
12   2308024310 23080243 郭窦 女 79 67 84 64 64 79 85
13  2308024435 23080244 姜毅涛 男 77 71 87 61 73 76 82
14   2308024432 23080244 赵宇 男 74 74 88 68 70 71 85
15   2308024446 23080244 周路 女 76 80 77 61 74 80 85
16  2308024421 23080244 林建祥 男 72 72 81 63 90 75 85
17  2308024433 23080244 李大强 男 79 76 77 78 70 70 89
18  2308024428 23080244 李侧通 男 64 96 91 69 60 77 83
19   2308024402 23080244 王慧 女 73 74 93 70 71 75 88
20  2308024422 23080244 李晓亮 男 85 60 85 72 72 83 89

### 1.2 增加一列“总分”并输出

,0,总分
0,学号 班级 姓名 性别 英语 体育 军训 数分 高代 解几 计算机,学号 班级 姓名 性别 英语 体育 军训 数分 高代 解几 计算机学号 班级 姓名 性别 英...
1,2308024241 23080242 成龙 男 76 78 77 40 23 60 89,2308024241 23080242 成龙 男 76 78 77 40 23 60 892...
2,2308024244 23080242 周怡 女 66 91 75 47 47 44 82,2308024244 23080242 周怡 女 66 91 75 47 47 44 822...
3,2308024251 23080242 张波 男 85 81 75 45 45 60 80,2308024251 23080242 张波 男 85 81 75 45 45 60 802...
4,2308024249 23080242 朱浩 男 65 50 80 72 62 71 82,2308024249 23080242 朱浩 男 65 50 80 72 62 71 822...
5,2308024219 23080242 封印 女 73 88 92 61 47 46 83,2308024219 23080242 封印 女 73 88 92 61 47 46 832...
6,2308024201 23080242 迟培 男 60 50 89 71 76 71 82,2308024201 23080242 迟培 男 60 50 89 71 76 71 822...
7,2308024347 23080243 李华 女 67 61 84 61 65 78 83,2308024347 23080243 李华 女 67 61 84 61 65 78 832...
8,2308024307 23080243 陈田 男 76 79 86 69 40 69 82,2308024307 23080243 陈田 男 76 79 86 69 40 69 822...
9,2308024326 23080243 余皓 男 66 67 85 65 61 71 95,2308024326 23080243 余皓 男 66 67 85 65 61 71 952...
10,2308024320 23080243 李嘉 女 62 60 90 60 67 77 95,2308024320 23080243 李嘉 女 62 60 90 60 67 77 952...
11,2308024342 23080243 李上初 男 76 90 84 60 66 60 82,2308024342 23080243 李上初 男 76 90 84 60 66 60 82...
12,2308024310 23080243 郭窦 女 79 67 84 64 64 79 85,2308024310 23080243 郭窦 女 79 67 84 64 64 79 852...
13,2308024435 23080244 姜毅涛 男 77 71 87 61 73 76 82,2308024435 23080244 姜毅涛 男 77 71 87 61 73 76 82...
14,2308024432 23080244 赵宇 男 74 74 88 68 70 71 85,2308024432 23080244 赵宇 男 74 74 88 68 70 71 852...
15,2308024446 23080244 周路 女 76 80 77 61 74 80 85,2308024446 23080244 周路 女 76 80 77 61 74 80 852...
16,2308024421 23080244 林建祥 男 72 72 81 63 90 75 85,2308024421 23080244 林建祥 男 72 72 81 63 90 75 85...
17,2308024433 23080244 李大强 男 79 76 77 78 70 70 89,2308024433 23080244 李大强 男 79 76 77 78 70 70 89...
18,2308024428 23080244 李侧通 男 64 96 91 69 60 77 83,2308024428 23080244 李侧通 男 64 96 91 69 60 77 83...
19,2308024402 23080244 王慧 女 73 74 93 70 71 75 88,2308024402 23080244 王慧 女 73 74 93 70 71 75 882...
20,2308024422 23080244 李晓亮 男 85 60 85 72 72 83 89,2308024422 23080244 李晓亮 男 85 60 85 72 72 83 89...

### 1.3 按班级、学号升序排序，并将排序结果覆盖原数据

### 1.4 按总分排名（要求名次符合常规考试中的排名规则），并将名次增加为一个新列保存至原DataFrame中

<font color='red'><B>思考：如何去掉名次后面的小数点与0，让名次以整数形式输出??</B></font>

### 1.5 按“总分排名”升序排序

## 任务二：数据读取、合并与保存
- （1） 利用pandas分别读取“数据1.csv”、“数据2.csv”两个文件中的数据，并保存至自定义的DateFrame对象中；
- （2） 分别尝试使用merge、join()、concat三种不同的方法对两个表中的数据进行合并；
- （3）保存合并后的结果至文件中。

### 2.1 读取数据

### 2.2 合并数据

#### 2.2.1 使用merge合并，输出合并后的前5项数据，并查看合并后的shape属性

#### 2.2.2 使用join()合并，输出合并后的前5项数据，并查看合并后的shape属性

#### 2.2.3 使用concat合并，输出合并后的前5项数据，并查看合并后的shape属性

### 2.3 保存合并后的数据至文件

### 2.4 读取保存后的数据至一个自定义的DataFrame中，并输出前5项